"""
This module reads the manifest.json file generated by react/vite
and retrieve the correct hashed filename
"""
import json
from pathlib import Path
from django.conf import settings

def get_vite_asset_path(asset_name):
    """Gets hashes generated by vite."""
    manifest_path = Path(settings.BASE_DIR) / "static/react/.vite/manifest.json"
    try:
        with open(manifest_path, 'r', encoding='utf-8') as f:
            manifest = json.load(f)
        # Adjust for directory prefix in manifest keys
        asset_key = f"react/{asset_name}"
        return f"{settings.STATIC_URL}{manifest[asset_key]['file']}"
    except FileNotFoundError:
        raise ValueError(f"Manifest file not found at {manifest_path}") from manifest_path
    except KeyError:
        raise ValueError(f"Asset '{asset_name}' not found in manifest") from asset_name
