services:
  postgres:
    image: postgres:latest
    platform: linux/amd64
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPWD}
    command: >
      postgres
      -c work_mem=64MB
      -c temp_buffers=32MB
      -c maintenance_work_mem=256MB
      -c max_connections=100
      -c shared_buffers=256MB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DBUSER} -d ${DBNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  web:
    build:
      context: .
    image: ${APP_NAME}:latest
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      DJANGO_SETTINGS_MODULE: physmagcalendar.settings
      APP_NAME: ${APP_NAME}
    depends_on:
      - postgres

  check_code:
    build:
      context: .
      dockerfile: Dockerfile.scripts
    command: /src/sdlc/check_code

    env_file:
      - ./.env
    depends_on:
      - web

  github_actions:
    build:
      context: .
      dockerfile: Dockerfile.act
    environment:
      DOCKER_USERNAME: ${DOCKER_USERNAME}
      DOCKER_ACCESS_TOKEN: ${DOCKER_ACCESS_TOKEN}
    command: /src/sdlc/gh_test
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Add this line
      - .:/src  # Also mount your source code
    depends_on:
      - web

volumes:
  postgres_data: