services:
  web:
    build: .
    image: ${APP_NAME}:latest
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      DJANGO_SETTINGS_MODULE: physmagcalendar.settings
      APP_NAME: ${APP_NAME}

  check_code:
    build:
      context: .
      dockerfile: Dockerfile.scripts
    command: /src/sdlc/check_code

    env_file:
      - ./.env
    depends_on:
      - web

  github_actions:
    build:
      context: .
      dockerfile: Dockerfile.act
    environment:
      DOCKER_USERNAME: ${DOCKER_USERNAME}
      DOCKER_ACCESS_TOKEN: ${DOCKER_ACCESS_TOKEN}
    command: /src/sdlc/gh_test
    env_file:
      - ./.env

volumes:
  postgres_data:
