# Generated by Django 4.2.6 on 2023-10-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_gyminfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gyminfo',
            name='email',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
