# Generated by Django 5.2.7 on 2025-10-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_uploadfile_delete_classtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gyminfo',
            old_name='gym_logo',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='gyminfo',
            name='feedback_form',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gyminfo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
