# Generated by Django 5.2.7 on 2025-10-31 21:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_gym_logo_gyminfo_logo_gyminfo_feedback_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gyminfo',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
